# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: David Naumann
title: Computer Engineer Undergraduate
email: NaumannDavidK@gmail.com
website: davidsprojects.us

# Social links
# twitter_username: DavidTheNewKid
github_username:  DavidNaumann
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: DavidTheNewKid
linkedin_username: david-naumann-1414b4128
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
about_title: Professional Summary
about_profile_image: images/davids_logo.png
about_content: | # this will include new lines to allow paragraphs
  Dedicated Computer Engineering student focused on applying advanced techinical expertise to a position in software testing and development.

  I am most skilled in: <mark>C++</mark> and <mark>Python</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Sections
more_title: Organizations
more_content: |
  Institute of Electrical and Electronic Engineers Student Membership:
    2017 - 2019

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
